### ISSUE TITLE
can you give a build dll ?

### ISSUE THREAD

**Issue by sum1201** [dearman/activizdotnet#1]
can you give a build dll ? thanks

**Comment by dearman** [comment]
I can post the binaries, but we might have to work on the redist dependences.

**Comment by sum1201** [comment]
thank you very much.
how long can i get the binaries?

**Comment by dearman** [comment]
Updated the readme with Binary Download
Visual Studio 2013 / ICC 2016 / CSC .NET 4.0 Debug Release http://www.cascadeacoustic.com/files/downloads/General/ActiViz_711d.zip

**Comment by sum1201** [comment]
thank you very much.
when i used it in visual studio 2013,i only add control to form ,run it  ,raise a exception:
"Kitware.VTK.WrappedObject" type initial value setting item raised exception.

**Comment by sum1201** [comment]
thank you very much . i can run it .
