### ISSUE TITLE
binaries for x64

### ISSUE THREAD

**Issue by shandoosheri** [dearman/activizdotnet#3]
Hi, I was wondering if you could post the binaries for a x64 version or if you have some sort of a guide on how i can build it myself.

Thank you

**Comment by dearman** [comment]
If you use the sources from my repo, you can just follow the Kitware build guide, without any additional changes.  I have also supplied example CMake configurations in each repo.  If there are upstream changes to VTK you need, you'll need to review my commits as examples of problem areas before merging them in.

**Comment by shandoosheri** [comment]
Thank you. I will give it a try.

**Comment by shandoosheri** [comment]
i am able to build mummy and vtk successfully but, when trying to build activiz i always get this type of error for a lot of files

78>------ Build started: Project: vtkRenderingFreeTypeGenerateCSharp, Configuration: Release x64 ------
78>  Building Custom Rule C:/Users/Shady/Desktop/VTK/activizdotnet/CMakeLists.txt
78>  CMake does not need to re-run because C:/Users/Shady/Desktop/VTK/activizdotnet-build/CMakeFiles/generate.stamp is up-to-date.
78>  Generating xml/vtkFreeTypeStringToImage.xml
78>  
78>  m_GCCXML_COMPILER: C:/Users/Shady/Desktop/VTK/activizdotnet-build/xml/vtkFreeTypeStringToImage_gccxml.cxx
78>  compilerName: vtkfreetypestringtoimage_gccxml.cxx
78>  compilerID: ERROR_unsupported_compiler_in_gxConfiguration_GetCompilerId
78>  
78>  Compiler "C:/Users/Shady/Desktop/VTK/activizdotnet-build/xml/vtkFreeTypeStringToImage_gccxml.cxx" is not supported by GCC_XML.
78>  (gxConfiguration::FindFlags)
78>  Could not determine GCCXML_FLAGS setting.
78>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(170,5): error MSB6006: "cmd.exe" exited with code 1.

Any suggestion on what could be the issue

**Comment by dearman** [comment]
You must use Visual Studio 2008 compilers for GCCXML/Mummy tasks.  So your build environment will normally consist of VC2008, your target .NET environment, like VS2013 in my case, and the C compiler you build VTK with, Intel C++ 2016 in my case.  All of these need to be configured via C Make variables.

**Comment by shandoosheri** [comment]
I figured that out eventually and i finally got everything to work. One of the things that i had trouble with is that i used the supplied binaries of gccxml instead of rebuilding a x64 version. Anyways, thanks alot for the great repo and all the help.
