### ISSUE TITLE
building with documentation

### ISSUE THREAD

**Issue by shandoosheri** [dearman/activizdotnet#4]
After finally being able to build this library, none of the classes seem to have any documentation on it unlike the previous version. i have configured vtk with the build documentation on but couldn't find a similar option for activiz. would you have suggestions on how to enable the documentaions

**Comment by dearman** [comment]
not sure, never looked at it.  I seem to recall its all done with doxygen.  If you figure out the issue please let me know.

**Comment by shandoosheri** [comment]
some of the  documentation seems to be missing some how. i got more classes to be documented by using the kitware.vtk.xml from vtk 5.8. i have attached the file here as well.
[Kitware.VTK.xml.zip](https://github.com/dearman/activizdotnet/files/1817176/Kitware.VTK.xml.zip)
