### ISSUE TITLE
It is possible update to 8.2 or 9.0 VTK

### ISSUE THREAD

**Issue by kiroo92** [dearman/activizdotnet#9]
It is possible update to 8.2 or 9.0 VTK

**Comment by dearman** [comment]
I don't think so on this code base.  I have no funding anymore. Haha.

**Comment by dearman** [comment]
I'm not saying it's not an easy update, but I just don't have the knowledge at this point, and you'd have to pay some one to really look into it.

**Comment by kiroo92** [comment]
Haha, thank you very much
